import type { Show } from './types';

// Pre-defined list of shows. Using names that are easy for TVMaze API to match.
export const SHOW_LIST: { name: string }[] = [
    { name: 'Breaking Bad' },
    { name: 'Game of Thrones' },
    { name: 'The Office' },
    { name: 'Friends' },
    { name: 'Stranger Things' },
    { name: 'The Mandalorian' },
    { name: 'The Witcher' },
    { name: 'Better Call Saul' },
    { name: 'Seinfeld' },
    { name: 'The Simpsons' },
    { name: 'Futurama' },
    { name: 'Rick and Morty' },
    { name: 'Chernobyl' },
    { name: 'Black Mirror' },
    { name: 'Westworld' },
    { name: 'The Crown' },
    { name: 'Fleabag' },
    { name: 'Parks and Recreation' },
    { name: 'Arrested Development' },
    { name: 'Succession' },
    { name: 'Ted Lasso' },
    { name: 'Squid Game' },
    { name: 'House of the Dragon' },
    { name: 'The Last of Us'},
    { name: 'Severance' },
    { name: "It's Always Sunny in Philadelphia" },
    { name: "Curb Your Enthusiasm" },
    { name: "Sherlock" },
    { name: "Doctor Who" },
    { name: "Star Trek: The Next Generation"},
    { name: "The X-Files"},
    { name: "Lost"},
    { name: "The Sopranos"},
    { name: "The Wire"},
    { name: "Mad Men"},
    { name: "The Americans"},
    { name: "Fargo"},
    { name: "True Detective"},
    { name: "Peaky Blinders"},
    { name: "Narcos"},
    { name: "Mindhunter"},
    { name: "Ozark"},
    { name: "Money Heist"},
    { name: "The Boys"},
    { name: "Invincible"},
    { name: "Arcane"},
    { name: "Attack on Titan"},
    { name: "Death Note"},
    { name: "Fullmetal Alchemist: Brotherhood"},
    { name: "Cowboy Bebop"},
    { name: "Avatar: The Last Airbender"},
    { name: "The Legend of Korra"},
    { name: "SpongeBob SquarePants"},
    { name: "South Park"},
    { name: "Family Guy"},
    { name: "American Dad!"},
    { name: "Bojack Horseman"},
    { name: "Community"},
    { name: "Modern Family"},
    { name: "Brooklyn Nine-Nine"},
    { name: "The Good Place"},
    { name: "Schitt's Creek"},
    { name: "Veep"},
    { name: "Silicon Valley"},
    { name: "Atlanta"},
    { name: "Barry"},
    { name: "The Marvelous Mrs. Maisel"},
    { name: "The Handmaid's Tale"},
    { name: "This Is Us"},
    { name: "Yellowstone"},
    { name: "The Walking Dead"},
    { name: "Dexter"},
    { name: "House"},
    { name: "Grey's Anatomy"},
    { name: "Supernatural"},
    { name: "The Vampire Diaries"},
    { name: "Buffy the Vampire Slayer"},
    { name: "Firefly"},
    { name: "Battlestar Galactica"},
    { name: "Stargate SG-1"},
    { name: "The Twilight Zone"},
    { name: "Twin Peaks"},
    { name: "Deadwood"},
    { name: "Rome"},
    { name: "Band of Brothers"},
    { name: "The Pacific"},
    { name: "Planet Earth"},
    { name: "Blue Planet II"},
    { name: "Cosmos"},
    { name: "Chef's Table"},
    { name: "The Great British Baking Show"},
    { name: "Queer Eye"},
    { name: "RuPaul's Drag Race"},
    { name: "Survivor"},
    { name: "The Bachelor"},
    { name: "Top Gear"},
    { name: "MythBusters"},
    { name: "How I Met Your Mother"},
    { name: "The Big Bang Theory"},
    { name: "Two and a Half Men"},
    { name: "New Girl"},
    { name: "How to Get Away with Murder"},
    { name: "Scandal"},
    { name: "Homeland"},
    { name: "24"},
    { name: "Prison Break"},
    { name: "Vikings"},
    { name: "The Last Kingdom"},
    { name: "Boardwalk Empire"},
    { name: "Sons of Anarchy"},
    { name: "Justified"},
    { name: "The Shield"},
    { name: "Six Feet Under"},
    { name: "Lost in Space"},
    { name: "The Expanse"},
    { name: "Dark"},
    { name: "Altered Carbon"},
    { name: "Sense8"},
    { name: "The OA"},
    { name: "Russian Doll"},
    { name: "Orange Is the New Black"},
    { name: "House of Cards"},
    { name: "Daredevil"},
    { name: "Jessica Jones"},
    { name: "Luke Cage"},
    { name: "Iron Fist"},
    { name: "The Punisher"},
    { name: "The Defenders"},
    { name: "Agents of S.H.I.E.L.D."},
    { name: "WandaVision"},
    { name: "Loki"},
    { name: "Hawkeye"},
    { name: "Moon Knight"},
    { name: "Ms. Marvel"},
    { name: "She-Hulk: Attorney at Law"},
    { name: "Andor"},
    { name: "Obi-Wan Kenobi"},
    { name: "The Book of Boba Fett"},
    { name: "Peacemaker"},
    { name: "Doom Patrol"},
    { name: "Titans"},
    { name: "Harley Quinn"},
    { name: "Young Justice"},
    { name: "The Venture Bros."},
    { name: "Archer"},
    { name: "Bob's Burgers"},
    { name: "King of the Hill"},
    { name: "Daria"},
    { name: "Beavis and Butt-Head"},
    { name: "What We Do in the Shadows"},
    { name: "Letterkenny"},
    { name: "Only Murders in the Building"},
    { name: "Adventure Time" },
    { name: "Smiling Friends" },
    { name: "Regular Show" },
    { name: "Gravity Falls" },
    { name: "Over the Garden Wall" },
    { name: "Steven Universe" },
    { name: "The Amazing World of Gumball" },
    { name: "Infinity Train" },
    { name: "Primal" },
    { name: "Samurai Jack" },
    { name: "The Dragon Prince" },
    { name: "Disenchantment" },
    { name: "Final Space" },
    { name: "Tuca & Bertie" },
    { name: "Solar Opposites" },
    { "name": "The Bear" },
    { "name": "Abbott Elementary" },
    { "name": "Reservation Dogs" },
    { "name": "Yellowjackets" },
    { "name": "Beef" },
    { "name": "The White Lotus" },
    { "name": "Killing Eve" },
    { "name": "Mr. Robot" },
    { "name": "Hannibal" },
    { "name": "Watchmen" },
    { "name": "The Leftovers" },
    { "name": "Better Things" },
    { "name": "GLOW" },
    { "name": "The Good Fight" },
    { "name": "Pose" },
    { "name": "What We Do in the Shadows" },
    { "name": "Taskmaster" },
    { "name": "Nathan for You" },
    { "name": "Review" },
    { "name": "Detroiters" },
    { "name": "I Think You Should Leave with Tim Robinson" },
    { "name": "Bluey" },
    { "name": "Hilda" },
    { "name": "Kipo and the Age of Wonderbeasts" },
    { "name": "She-Ra and the Princesses of Power" },
    { "name": "The Owl House" },
    { "name": "Amphibia" },
    { "name": "One-Punch Man" },
    { "name": "Mob Psycho 100" },
    { "name": "Jujutsu Kaisen" },
    { "name": "Demon Slayer: Kimetsu no Yaiba" },
    { "name": "Vinland Saga" }
];